all:
  hosts:
    mail:
      ansible_host: 66.78.40.21
      ansible_user: ansible
# uncomment this on error, is not required depending on your venv setup
#      ansible_ssh_private_key_file: keyfile
      ansible_python_interpreter: /usr/bin/python3
      become: yes
